### ISSUE TITLE
Use units not strings

### ISSUE THREAD

**Issue by getdave** [csswizardry/csswizardry-grids#2]
First off, let me say "great job" for your work on this. Really excellent stuff.

Having worked with developers in the past they often complained to me that my string-based CSS grid selectors were difficult to work with when generating grids dynamically using a server-side language.

Would it be worth considering aliasing the string-based selectors (eg: `.one-half`) for unit based versions (eg: `.1-2`) ? Would be easier to generate in a PHP `for` loop for example.

Would be very interested to hear your thoughts.

**Comment by dkisselev** [comment]
I'm not a professional by any means, so I might be missing something, but having worked with PHP, in terms of how you would write a program, .one-half is just as much a string as .1-2

Even if you wanted to mathematically calculate that you can fit two .1-2 blocks into the space of a .1 block, you would still need to make sure the program knows that only certain fractions are available, otherwise it would try to do things like .5-22. And if you're building up an array of "available fractions" it's just as easy to use words as it is numbers.

I hope this isn't coming off like I'm bashing the idea, I just think the developers might be referring to something different when they say no string-based grid selectors.

**Comment by KittyGiraudel** [comment]
You can write a for loop for like this:

```
for($i = 0; $i < $limit; $i++) {
  $dump = "&lt;div class=\"" . $i . "-" . $i + 1 . "\">&lt;/div>";
}
```

You can't do something like that with string based class names like "one, two, three, four".

**Comment by csswizardry** [comment]
Whilst I do get your point, the idea of using numbers kinds of flies in the face of this method. However, if you require this functionality then feel free to make a fork of this code with the new classes :)

Cheers,
H

**Comment by amitkaz** [comment]
I've created a fork with numbers instead of strings- as a nice side effect, the whole explosion generation is really simple (via sass loop/function)
Units like %s-1-5, %desk-3-24 etc.

https://github.com/amitkaz/gridsplosion

@getdave @HugoGiraudel, what do you think?

**Comment by KittyGiraudel** [comment]
Pretty tight code, I like that. Thanks for your work. :)

**Comment by getdave** [comment]
Looks good. Implemented something similar on my own grid framework. Nice
work!

**Comment by mikko-kohtala** [comment]
amitkaz, awesome fork, and the code looks so beautiful :+1:

**Comment by amitkaz** [comment]
Thanks guys :)

**Comment by csswizardry** [comment]
I know this is a solved problem now, but I have added [a branch](https://github.com/csswizardry/csswizardry-grids/blob/feature/numbers/csswizardry-grids.scss#L119-L204) to csswizardry-grids that allows you to use numeric classes, e.g.:

```
<div class="grid">
    <div class="grid__item  1/2  desk-1/4>
        foo
    </div><!--
 --><div class="grid__item  1/2  desk-1/4>
        foo
    </div><!--
 --><div class="grid__item  1/2  desk-1/4>
        foo
    </div><!--
 --><div class="grid__item  1/2  desk-1/4>
        foo
    </div>
</div>
```
